spring.datasource.url=${DB_REFERENCE_URL}
spring.datasource.username=${DB_REFERENCE_USERNAME}
spring.datasource.password=${DB_REFERENCE_PASSWORD}

spring.main.web-application-type=none
spring.liquibase.enabled=false
spring.jpa.hibernate.ddl-auto=create
